- hosts: dummy
  gather_facts: false
  vars:
  tasks:
    - name: Create user account
      ansible.builtin.user:
        create_home: true
        generate_ssh_key: false
        name: foobar1
        shell: /bin/bash
